<a href="https://colab.research.google.com/github/Vishnuvardhan172709/Aiml-/blob/main/assignment%201%20(part1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#implementing list using numpy
import numpy as np
print(1.1)
list=np.array([3,5,7,8])
print(list)

1.1
[3 5 7 8]


In [ ]:
#implementing array using numpy
import numpy as np
print(1.2)
array=np.array([3, 0, 3, 2, 1, 6, 2, 8])
print("Array: ",array)

1.2
Array:  [3 0 3 2 1 6 2 8]


In [ ]:
#implementing type() using numpy
import numpy as np
print(1.3)
array_1D=np.array([1, 2, 3, 4, 5])
print("1D Array Type: ",type(array_1D))

1.3
1D Array Type:  <class 'numpy.ndarray'>


In [ ]:
#from _future_ import division
#Performing mathematical operations
import numpy as np
print(1.4)
a=np.array([3, 8, 9, 8])
b=np.array([1, 2, 3, 4])
#Multiplication
multiply=np.multiply(a, b)
print(multiply)
#Division
division=np.divide(a, b)
print(division)
#poweroff
power=np.power(a,b)
print(power)

1.4
[ 3 16 27 32]
[3. 4. 3. 2.]
[   3   64  729 4096]


In [ ]:
#Addition of Two arrays
import numpy as np
print(1.5)
arr1=np.array([1, 6, 2, 6])
arr2=np.array([3, 5, 7, 8])
addition=arr1+arr2
print(addition)

1.5
[ 4 11  9 14]


In [ ]:
#implement np.sin(), log(), np.exp(), log2()
import numpy as np
print(1.6)
a = np.array([1,2,3])
sin = np.sin(a)
print(sin)
log = np.log(a)
print(log)
exp = np.exp(a)
print(exp)
log2 = np.log2(a)
print(log2)

1.6
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
[0.        1.        1.5849625]
